yelp_clone/config/routes.rb
Rails.application.routes.draw do

  root to: "restaurants#index"

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :restaurants, shallow: true do
    resources :reviews do
      resources :endorsements
    end
  end 

end

yelp_clone/app/models/endorsement.rb
class Endorsement < ActiveRecord::Base
  belongs_to :review
end

yelp_clone/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  has_many :reviews, dependent: :destroy
  belongs_to :user
  validates :name, length: {minimum: 3}, uniqueness: true

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
 validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  def average_rating
    return 'N/A' if reviews.none?
    reviews.inject(0) {|memo, review| memo + review.rating} / reviews.length
  end

  def build_review(attributes = {}, user)
    review = reviews.build(attributes)
    review.user = user
    review
  end
end

yelp_clone/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  has_many :endorsements, dependent: :destroy
  validates :rating, inclusion: (1..5)
  validates :user, uniqueness: { scope: :restaurant, message: "has reviewed this restaurant already" }


end

yelp_clone/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :reviews
  has_many :restaurants
  has_many :reviewed_restaurants, through: :reviews, source: :restaurant
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  def has_reviewed?(restaurant)
    reviewed_restaurants.include? restaurant
  end

 def self.from_omniauth(auth)
   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
     user.email = auth.info.email
     user.password = Devise.friendly_token[0,20]
   end
 end

 def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
     end
   end
 end
end

yelp_clone/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
end

yelp_clone/app/controllers/endorsements_controller.rb
class EndorsementsController < ApplicationController

  def create
    @review = Review.find(params[:review_id])
    @review.endorsements.create
     render json: {new_endorsement_count: @review.endorsements.count}
  end

end

yelp_clone/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]
  before_action :check_author, :only => [:edit, :update, :destroy]

  def check_author
    if current_user.id != Restaurant.find(params[:id]).user_id
      flash[:notice] = 'nope'
      redirect_to '/restaurants' and return
    end
  end

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def restaurant_params
    new_params = params.require(:restaurant).permit(:name, :image)
    new_params[:user_id] = current_user.id
    new_params
  end

  def create
    @restaurant = Restaurant.create(restaurant_params)
    if @restaurant.save
      redirect_to '/restaurants'
    else
      render 'new'
    end
  end

  def show
    @restaurant = Restaurant.find(params[:id])
  end

  def edit
    @restaurant = Restaurant.find(params[:id])
  end

  def update
    @restaurant = Restaurant.find(params[:id])
    @restaurant.update(restaurant_params)
    redirect_to '/restaurants'
  end

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    flash[:notice] = 'Restaurant deleted successfully'
    redirect_to '/restaurants'
  end


end

yelp_clone/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!, :except => [:index, :show]
  before_action :check_author, :only => [:destroy]

  def check_author
    if current_user.id != Review.find(params[:id]).user_id
      flash[:notice] = 'no'
      redirect_to '/restaurants' and return
    end
  end

  def review_params
    params.require(:review).permit(:thoughts, :rating)
  end

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    flash[:notice] = 'Review deleted successfully'
    redirect_to '/restaurants'
  end

  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.build_review review_params, current_user

    if @review.save
      redirect_to restaurants_path
    else
      if @review.errors[:user]
        # Note: if you have correctly disabled the review button where appropriate,
        # this should never happen...
        redirect_to restaurants_path, alert: 'You have already reviewed this restaurant'
      else
        # Why would we render new again?  What else could cause an error?
        render :new
      end
    end
  end
end

yelp_clone/app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook

    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url

    end
  end

  def failure
    redirect_to root_path
  end
end

yelp_clone/app/helpers/application_helper.rb
module ApplicationHelper
end

yelp_clone/app/helpers/endorsements_helper.rb
module EndorsementsHelper
end

yelp_clone/app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

yelp_clone/app/helpers/reviews_helper.rb
module ReviewsHelper
  def star_rating(rating)
    return rating unless rating.respond_to?(:round)
    remainder = (5 - rating)
    "★" * rating.round + "☆" * remainder
  end
end

yelp_clone/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
   <meta charset="UTF-8">
  <title>YelpClone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <br>
  <div id="main-container" class="container-fluid">
    <div class="row">
      <div class="col-md-8">
        <div class="navbar-header">
        <a href="/restaurants" class="btn btn-info" role="button">Home</a>&nbsp;
  <% if user_signed_in? %>
    <%= link_to "Sign out", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to "Sign in", new_user_session_path %> |
    <%= link_to "Sign up", new_user_registration_path %> |
    <%= link_to "Sign in with Facebook", user_omniauth_authorize_path(:facebook) %>
  <% end %>
      </div>
      <br>
  <%= notice %>
  <%= alert %>
      </div>
      <div class="col-md-6">
        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>

yelp_clone/app/views/restaurants/_form.html.erb
<div class="form-group">
<%= form_for @restaurant, html: {multiple: true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
</div>
<div class="form-group">
  <%= f.file_field :image %>
  </div>
  <%= f.submit %>
<% end %>

yelp_clone/app/views/restaurants/edit.html.erb
<%= render "form" %>

yelp_clone/app/views/restaurants/index.html.erb
<br>
<a href='/restaurants/new'>Add a restaurant</a>

<% if @restaurants.any? %>
<% @restaurants.each do |restaurant| %>
<h3>
  <%= link_to restaurant.name, restaurant_path(restaurant) %>

</h3>
<p>
  <%= image_tag restaurant.image.url(:thumb) %>
</p>
<p>
  <%= link_to "Edit #{restaurant.name} | ", edit_restaurant_path(restaurant) %>
  <%= link_to "Delete #{restaurant.name} | ", restaurant_path(restaurant), method: :delete %>
  <%= link_to "Review #{restaurant.name}", new_restaurant_review_path(restaurant) %>

</p>

<h3>Reviews for <%= restaurant.name %></h3>

<% if restaurant.reviews.any? %>
<ul>
  <% restaurant.reviews.each do |review| %>
  <li>
    <%= review.thoughts  %> <strong><%= review.rating  %></strong>/5
    <%= link_to "Endorse", review_endorsements_path(review), class: 'endorsements-link' %>
      <span class="endorsements_count"> <%= review.endorsements.count %> </span> <%= 'endorsement'.pluralize(review.endorsements.count) %>
    <%= link_to " Delete Review", "/reviews/#{review.id}", method: :delete %>
  </li>

  <% end %>
</ul>
<% else %>
<p>No reviews.</p>
<% end %>
<h4>Average rating: <%= star_rating(restaurant.average_rating) %></h4>

<% end %>
<% else %>
No restaurants yet
<% end %>

yelp_clone/app/views/restaurants/new.html.erb
<% if @restaurant.errors.any? %>
  <section id="errors">
    <h2> <%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved: </h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
    </section>
    <% end %>

<%= render "form" %>

yelp_clone/app/views/restaurants/show.html.erb
<p><%= @restaurant.name %></p>
<p><%= @restaurant.description %></p>

yelp_clone/app/views/reviews/new.html.erb
<%= form_for [@restaurant, @review] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.label :rating %>
  <%= f.select :rating, (1..5) %>
  <%= f.submit 'Leave Review' %>
<% end %>